version: "3.5"

networks:
  localhost:
    name: inet

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/d/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/d/data/mariadb
      o: bind
      type: none


services:
  mariadb:  
    container_name: mariadb_debian
    build:
      context: ./mariadb
      args:
        DB_NAME: ${ENV_DB_NAME}
        DB_USER: ${ENV_DB_USER}
        DB_PASS: ${ENV_DB_PASS}
        DB_ROOT_PASS: ${ENV_DB_ROOT_PASS}
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - localhost
    image: mariadb
    restart: always

  nginx:
    depends_on:
      - wordpress
    container_name: nginx_debian
    build: ./nginx
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - localhost
    restart: always

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress_debian
    build:
      context: ./wordpress
      args:
        DB_NAME: ${ENV_DB_NAME}
        DB_USER: ${ENV_DB_USER}
        DB_PASS: ${ENV_DB_PASS}
        DB_HOST: ${ENV_DB_HOST}
        # WP_URL: ${ENV_WP_URL}
        # WP_TITLE: ${ENV_WP_TITLE}
        # WP_ADMIN_NICK: ${ENV_WP_ADMIN_NICK}
        # WP_ADMIN_PASS: ${ENV_WP_ADMIN_PASS}
        # WP_ADMIN_MAIL: ${ENV_WP_ADMIN_MAIL}
        # WP_USER_NICK: ${ENV_WP_USER_NICK}
        # WP_USER_MAIL: ${ENV_WP_USER_MAIL}
        # WP_USER_PASS: ${ENV_WP_USER_PASS}
    image: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - localhost
    restart: always
    environment:
      - WP_URL=${ENV_WP_URL}
      - WP_TITLE=${ENV_WP_TITLE}
      - WP_ADMIN_NICK=${ENV_WP_ADMIN_NICK}
      - WP_ADMIN_PASS=${ENV_WP_ADMIN_PASS}
      - WP_ADMIN_MAIL=${ENV_WP_ADMIN_MAIL}
      - WP_USER_NICK=${ENV_WP_USER_NICK}
      - WP_USER_MAIL=${ENV_WP_USER_MAIL}
      - WP_USER_PASS=${ENV_WP_USER_PASS}
